name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '16'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
