version: 0.2

phases:
  pre_build:
    commands:
      - yarn install
      - yarn lint
  build:
    commands:
      - yarn build
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/apps'
  secondary-artifacts:
    api:
      files:
        - '**/*'
      base-directory: 'dist/apps/api'
      name: lets-choose-api
    client:
      files:
        - '**/*'
      base-directory: 'dist/apps/client'
      name: lets-choose-client
