version: 0.2

phases:
  pre_build:
    commands:
      - yarn install
      - yarn lint
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - ls -R ./dist | awk '
        /:$/&&f{s=$0;f=0}
        /:$/&&!f{sub(/:$/,"");s=$0;f=1;next}
        NF&&f{ print s"/"$0 }'
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/apps'
  secondary-artifacts:
    api:
      files:
        - '**/*'
      base-directory: 'dist/apps/api'
      name: lets-choose-api
    client:
      files:
        - '**/*'
      base-directory: 'dist/apps/client'
      name: lets-choose-client
