version: 0.2

phases:
  pre_build:
    commands:
      - yarn install
      - yarn lint
  build:
    commands:
      - yarn build
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - 'dist/apps/api/**/*'
  name: lets-choose-api
  s3-prefix: lets-choose
  secondary-artifacts:
    client:
      files:
        - 'dist/apps/client/**/*'
      name: lets-choose-client
