version: "3.8"
services:
  web:
    build: .
    image: ${DOCKER_REGISTRY}/lets-choose:latest
    container_name: "lets-choose"
    ports:
      - "80:3000"
    env_file: packages/server/.env
volumes:
  logvolume01: {}
