version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    image: ${DOCKER_REGISTRY}/lets-choose-api:latest
    container_name: "lets-choose-api"
    env_file: ./.env
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    image: ${DOCKER_REGISTRY}/lets-choose-client:latest
    container_name: "lets-choose-client"
    env_file: ./.env
    environment:
      - PORT=80
      - API_URL=http://api:5000
    ports:
      - "80:80"
    depends_on:
      - api
    links:
      - api:api
volumes:
  logvolume01: {}
