export enum TYPES {
  AuthService = 'AuthService',
  UserService = 'UserService',
  JwtService = 'JwtService',
  GameService = 'GameService',
  EmailService = 'EmailService',
  ContestService = 'ContestService',
  CloudinaryService = 'CloudinaryService',
  PasswordHashService = 'PasswordHashService',
  UserRepository = 'UserRepository',
  ContestRepository = 'ContestRepository',
  GameRepository = 'GameRepository',
  ContestItemRepository = 'ContestItemRepository',
  AuthMiddleware = 'AuthMiddleware',
  IsAuthorMiddleware = 'IsAuthorMiddleware',
  AuthController = 'AuthController',
  UserController = 'UserController',
  ContestController = 'ContestController',
  GameController = 'GameController',
  TaskController = 'TaskController',
}
